package linkmonitor

type rdmaCounterField struct {
	metric string
	scale  uint64
}

// Linux sysfs ABI and the reviewed node_exporter mappings. The data registers
// count four-octet units, independent of the number of active lanes.
var rdmaCounterCatalog = map[string]rdmaCounterField{
	"counters/excessive_buffer_overrun_errors": {"excessive_buffer_overrun_errors_total", 1},
	"counters/link_downed":                     {"link_downed_total", 1},
	"counters/link_error_recovery":             {"link_error_recovery_total", 1},
	"counters/local_link_integrity_errors":     {"local_link_integrity_errors_total", 1},
	"counters/multicast_rcv_packets":           {"multicast_packets_received_total", 1},
	"counters/multicast_xmit_packets":          {"multicast_packets_transmitted_total", 1},
	"counters/port_rcv_constraint_errors":      {"port_constraint_errors_received_total", 1},
	"counters/port_rcv_data":                   {"port_data_received_bytes_total", 4},
	"counters/port_rcv_discards":               {"port_discards_received_total", 1},
	"counters/port_rcv_errors":                 {"port_errors_received_total", 1},
	"counters/port_rcv_packets":                {"port_packets_received_total", 1},
	"counters/port_rcv_remote_physical_errors": {"port_receive_remote_physical_errors_total", 1},
	"counters/port_rcv_switch_relay_errors":    {"port_receive_switch_relay_errors_total", 1},
	"counters/port_xmit_constraint_errors":     {"port_constraint_errors_transmitted_total", 1},
	"counters/port_xmit_data":                  {"port_data_transmitted_bytes_total", 4},
	"counters/port_xmit_discards":              {"port_discards_transmitted_total", 1},
	"counters/port_xmit_packets":               {"port_packets_transmitted_total", 1},
	"counters/port_xmit_wait":                  {"port_transmit_wait_total", 1},
	"counters/symbol_error":                    {"symbol_error_total", 1},
	"counters/unicast_rcv_packets":             {"unicast_packets_received_total", 1},
	"counters/unicast_xmit_packets":            {"unicast_packets_transmitted_total", 1},
	"counters/VL15_dropped":                    {"vl15_dropped_total", 1},
	"counters_ext/port_multicast_rcv_packets":  {"legacy_multicast_packets_received_total", 1},
	"counters_ext/port_multicast_xmit_packets": {"legacy_multicast_packets_transmitted_total", 1},
	"counters_ext/port_rcv_data_64":            {"legacy_data_received_bytes_total", 4},
	"counters_ext/port_rcv_packets_64":         {"legacy_packets_received_total", 1},
	"counters_ext/port_unicast_rcv_packets":    {"legacy_unicast_packets_received_total", 1},
	"counters_ext/port_unicast_xmit_packets":   {"legacy_unicast_packets_transmitted_total", 1},
	"counters_ext/port_xmit_data_64":           {"legacy_data_transmitted_bytes_total", 4},
	"counters_ext/port_xmit_packets_64":        {"legacy_packets_transmitted_total", 1},
	"hw_counters/duplicate_request":            {"duplicate_requests_packets_total", 1},
	"hw_counters/implied_nak_seq_err":          {"implied_nak_seq_errors_total", 1},
	"hw_counters/lifespan":                     {"lifespan_seconds", 0},
	"hw_counters/local_ack_timeout_err":        {"local_ack_timeout_errors_total", 1},
	"hw_counters/np_cnp_sent":                  {"np_cnp_packets_sent_total", 1},
	"hw_counters/np_ecn_marked_roce_packets":   {"np_ecn_marked_roce_packets_received_total", 1},
	"hw_counters/out_of_buffer":                {"out_of_buffer_drops_total", 1},
	"hw_counters/out_of_sequence":              {"out_of_sequence_packets_received_total", 1},
	"hw_counters/packet_seq_err":               {"packet_sequence_errors_total", 1},
	"hw_counters/req_cqe_error":                {"req_cqes_errors_total", 1},
	"hw_counters/req_cqe_flush_error":          {"req_cqes_flush_errors_total", 1},
	"hw_counters/req_remote_access_errors":     {"req_remote_access_errors_total", 1},
	"hw_counters/req_remote_invalid_request":   {"req_remote_invalid_request_errors_total", 1},
	"hw_counters/resp_cqe_error":               {"resp_cqes_errors_total", 1},
	"hw_counters/resp_cqe_flush_error":         {"resp_cqes_flush_errors_total", 1},
	"hw_counters/resp_local_length_error":      {"resp_local_length_errors_total", 1},
	"hw_counters/resp_remote_access_errors":    {"resp_remote_access_errors_total", 1},
	"hw_counters/rnr_nak_retry_err":            {"rnr_nak_retry_packets_received_total", 1},
	"hw_counters/roce_adp_retrans":             {"roce_adp_retransmits_total", 1},
	"hw_counters/roce_adp_retrans_to":          {"roce_adp_retransmits_timeout_total", 1},
	"hw_counters/roce_slow_restart":            {"roce_slow_restart_used_total", 1},
	"hw_counters/roce_slow_restart_cnps":       {"roce_slow_restart_cnps_total", 1},
	"hw_counters/roce_slow_restart_trans":      {"roce_slow_restart_total", 1},
	"hw_counters/rp_cnp_handled":               {"rp_cnp_packets_handled_total", 1},
	"hw_counters/rp_cnp_ignored":               {"rp_cnp_ignored_packets_received_total", 1},
	"hw_counters/rx_atomic_requests":           {"rx_atomic_requests_total", 1},
	"hw_counters/rx_dct_connect":               {"rx_dct_connect_requests_total", 1},
	"hw_counters/rx_icrc_encapsulated":         {"rx_icrc_encapsulated_errors_total", 1},
	"hw_counters/rx_read_requests":             {"rx_read_requests_total", 1},
	"hw_counters/rx_write_requests":            {"rx_write_requests_total", 1},
}
