schema = 3

[mod]
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/dgryski/go-rendezvous"]
    version = "v0.0.0-20200823014737-9f7001d12a5f"
    hash = "sha256-n/7xo5CQqo4yLaWMSzSN1Muk/oqK6O5dgDOFWapeDUI="
  [mod."github.com/felixge/fgprof"]
    version = "v0.9.5"
    hash = "sha256-YhllfK5CbgWotxGgu/Y00xEP8YurStZZf4cYBtJHrQg="
  [mod."github.com/golang/snappy"]
    version = "v0.0.4"
    hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="
  [mod."github.com/google/pprof"]
    version = "v0.0.0-20241017200806-017d972448fc"
    hash = "sha256-7qp4s0jA/SRjgyCU65Vd6sVf5taoDoGBP+MhcXW1m/g="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.11"
    hash = "sha256-LFSIWy0C4VbiuPve0eKHr7Q7s4XtaGzsZ3qpO+6bEgc="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/nats-io/nats.go"]
    version = "v1.37.0"
    hash = "sha256-CX8oBIlpcxCNt5xDbxh79AnN+S9E8Y4FqjhIGVG5pQ8="
  [mod."github.com/nats-io/nkeys"]
    version = "v0.4.7"
    hash = "sha256-ui/vSa2TGe6Pe2aAzitBa1Pd2vKgTMuHoBhYYy2p6Rw="
  [mod."github.com/nats-io/nuid"]
    version = "v1.0.1"
    hash = "sha256-7wddxVz3hnFg/Pf+61+MtQJJL/l8EaC8brHoNsmD64c="
  [mod."github.com/nsqio/go-nsq"]
    version = "v1.1.0"
    hash = "sha256-/xHwwyRJLscNssHcYTVyqudSYeMwraREODKlmPXYxdo="
  [mod."github.com/pierrec/lz4/v4"]
    version = "v4.1.21"
    hash = "sha256-u47Lm4tN2ChGDLGyR+Jpi/Mi0bOFBVT6PTpPFdu2rMU="
  [mod."github.com/pkg/profile"]
    version = "v1.7.0"
    hash = "sha256-wd8L8WiPoojo/oVUshgiJdM/k367LL1XO5BL5u1L2UU="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.20.5"
    hash = "sha256-RbDZTBH+j2ZNLbHSMFxW0j8UStvkwc4IHTz3My9w4qo="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.1"
    hash = "sha256-rIDyUzNfxRA934PIoySR0EhuBbZVRK/25Jlc/r8WODw="
  [mod."github.com/prometheus/common"]
    version = "v0.60.0"
    hash = "sha256-olykcW7bZOWAH8VrYqP+8Tf5a+0kfiHcT2QF492j2KI="
  [mod."github.com/prometheus/procfs"]
    version = "v0.15.1"
    hash = "sha256-H+WXJemFFwdoglmD6p7JRjrJJZmIVAmJwYmLbZ8Q9sw="
  [mod."github.com/redis/go-redis/v9"]
    version = "v9.6.1"
    hash = "sha256-ROJwKA0ioyh1JQbINnLH/0z8O/Kj9/1VctIS6nmaP4E="
  [mod."github.com/twmb/franz-go"]
    version = "v1.18.0"
    hash = "sha256-EtNCDSSGHJl0+Tk8mRJCxHwmtS15f2AmGxVr5X2jGb0="
  [mod."github.com/twmb/franz-go/pkg/kmsg"]
    version = "v1.9.0"
    hash = "sha256-HZ6mShBBXrqqbEJmUeMmbijZgCldHDtYzoWhydXGSg4="
  [mod."github.com/twmb/franz-go/plugin/kprom"]
    version = "v1.1.0"
    hash = "sha256-CtfOzV2a4NUJRQ/l00zPSdnVG6epVDXJXg5i6o6P3K4="
  [mod."github.com/vmihailenco/msgpack/v5"]
    version = "v5.4.1"
    hash = "sha256-pDplX6xU6UpNLcFbO1pRREW5vCnSPvSU+ojAwFDv3Hk="
  [mod."github.com/vmihailenco/tagparser/v2"]
    version = "v2.0.0"
    hash = "sha256-M9QyaKhSmmYwsJk7gkjtqu9PuiqZHSmTkous8VWkWY0="
  [mod."golang.org/x/crypto"]
    version = "v0.28.0"
    hash = "sha256-AYjr0BcWQMwWY1u8c2hzUprtqHUmAH7RNSxHz2hhnZs="
  [mod."golang.org/x/net"]
    version = "v0.30.0"
    hash = "sha256-i1f6wJHfFq0nKtbuY7twZ7uPyUbRYHVjd3uy0SS06mU="
  [mod."golang.org/x/sys"]
    version = "v0.26.0"
    hash = "sha256-YjklsWNhx4g4TaWRWfFe1TMFKujbqiaNvZ38bfI35fM="
  [mod."golang.org/x/text"]
    version = "v0.19.0"
    hash = "sha256-C92pSYLLUQ2NKKcc60wpoSJ5UWAfnWkmd997C13fXdU="
  [mod."golang.org/x/time"]
    version = "v0.7.0"
    hash = "sha256-o1ol/hTpfrc06KUXSepAgm4QUuWmH1S+vqg6kmFad64="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20241015192408-796eee8c2d53"
    hash = "sha256-Fk+cG5bRI3BvnqhWzvMzbU36cC7PM+o2oAOJmvVx9M0="
  [mod."google.golang.org/grpc"]
    version = "v1.67.1"
    hash = "sha256-VqfKp80c2B1MK4m1WtHW4r7ykqdChJbqaMn+gMEYmYc="
  [mod."google.golang.org/protobuf"]
    version = "v1.35.1"
    hash = "sha256-4NtUQoBvlPGFGjo7c+E1EBS/sb8oy50MGy45KGWPpWo="
