t:
	go test -v

testd:
	go test --run TestDeserializeNlMsgHdrLengthAndType

testi:
	go test --run TestDeserializeInetDiagMsg

testSize:
	go test --run TestVerifySizeOfStructs

b:
	go test -bench=.

ben:
	go test -bench=BenchmarkSerializeTo -benchtime=20s

