package xtcpnl

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"syscall"
	"testing"

	"golang.org/x/sys/unix"
)

type linkCaptureMessage struct {
	protocol uint16
	header   NlMsgHdr
	wire     []byte
	body     []byte
}

// Do not reuse the old one-message/one-record fixture readers. nlmon mixes
// socket protocols, records contain multiple aligned messages, and duplicate
// deliveries are normal. This adapter retains all messages, including ACKs.
func readLinkCapture(t testing.TB, path string) []linkCaptureMessage {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	_, records, err := ParseNetlinkPcap(data)
	if err != nil {
		t.Fatal(err)
	}
	var result []linkCaptureMessage
	for i, record := range records {
		if record.Header.CapLen != record.Header.Len {
			t.Fatalf("%s record %d: snaplen truncation", path, i)
		}
		protocol, body, err := record.NetlinkPayload()
		if err != nil {
			t.Fatal(err)
		}
		if binary.BigEndian.Uint16(record.Data[2:4]) != 824 {
			t.Fatalf("%s: not ARPHRD_NETLINK", path)
		}
		for len(body) > 0 {
			var h NlMsgHdr
			if _, err := DeserializeNlMsgHdr(body, &h); err != nil {
				t.Fatal(err)
			}
			if h.Len < 16 || uint64(h.Len) > uint64(len(body)) {
				t.Fatalf("%s: invalid message length %d", path, h.Len)
			}
			n := int(h.Len)
			result = append(result, linkCaptureMessage{protocol, h, body[:n], body[16:n]})
			if n == len(body) {
				break
			}
			aligned := (n + 3) &^ 3
			if aligned > len(body) {
				t.Fatalf("%s: partial message padding", path)
			}
			body = body[aligned:]
		}
	}
	if len(result) == 0 {
		t.Fatalf("%s: empty fixture", path)
	}
	return result
}

func linkCaptureBundle(t *testing.T, kernel, scenario string) []linkCaptureMessage {
	t.Helper()
	dir := filepath.Join("testdata", kernel, "link-state", "matrix-vm-all-20261005", scenario)
	all := readLinkCapture(t, filepath.Join(dir, "raw.pcap"))
	for name, protocol := range map[string]uint16{"route": 0, "generic": 16} {
		var filtered []linkCaptureMessage
		for _, m := range all {
			if m.protocol == protocol {
				filtered = append(filtered, m)
			}
		}
		derived := readLinkCapture(t, filepath.Join(dir, name+".pcap"))
		if !reflect.DeepEqual(filtered, derived) {
			t.Fatalf("%s: raw/%s projection differs", scenario, name)
		}
	}
	return all
}

func equalScalar[T comparable](got *T, want T) bool { return got != nil && *got == want }

// nlmon records the header a CLI sends before autobind, which can contain
// PID zero. Resolve that socket's port from a captured ACK's original header,
// not a wildcard PID match. A SET sharing a sequence must not satisfy a GET.
func linkFixtureMatchesGET(request, reply linkCaptureMessage, kind EthtoolKind, packets []linkCaptureMessage) bool {
	get := map[EthtoolKind]byte{EthtoolLinkInfoKind: 2, EthtoolLinkModesKind: 4, EthtoolLinkStateKind: 6, EthtoolRingsKind: 15, EthtoolPauseKind: 21, EthtoolFECKind: 29}[kind]
	if len(request.body) < 4 || request.body[0] != get || request.header.Seq != reply.header.Seq {
		return false
	}
	if request.header.Pid != 0 {
		return request.header.Pid == reply.header.Pid
	}
	ports := make(map[uint32]bool)
	for _, ack := range packets {
		if ack.protocol == request.protocol && ack.header.Type == unix.NLMSG_ERROR && ack.header.Seq == request.header.Seq && len(ack.body) >= 20 && bytes.Equal(request.wire[:16], ack.body[4:20]) {
			ports[ack.header.Pid] = true
		}
	}
	return len(ports) == 1 && ports[reply.header.Pid]
}

// Each outcome below comes from the capture operation and independent
// ip/ethtool/nlprobe sidecars, not a golden generated by ParseEthtool.
// Simulator and virtio values are wire evidence, NOT physical negotiation.
func TestLinkStateKernelFixtures(t *testing.T) {
	type row struct {
		scenario, description, outcome string
		kind                           EthtoolKind
		device                         string
		errno                          syscall.Errno
		notify                         bool
		check                          func(EthtoolMessage) bool
	}
	modes := func(speed uint32, duplex uint8) func(EthtoolMessage) bool {
		return func(m EthtoolMessage) bool {
			v := m.LinkModes
			return v != nil && equalScalar(v.Speed, speed) && equalScalar(v.Duplex, duplex)
		}
	}
	baseRows := []row{
		{"cli-query", "independent CLI query", "unknown speed and duplex remain present", EthtoolLinkModesKind, "nltest0", 0, false, modes(0xffffffff, 255)},
		{"info", "virtual NIC identity", "port other, PHY address zero, internal transceiver", EthtoolLinkInfoKind, "nltest0", 0, false, func(m EthtoolMessage) bool {
			return m.LinkInfo != nil && equalScalar(m.LinkInfo.Port, uint8(255)) && equalScalar(m.LinkInfo.PHYAddress, uint8(0)) && equalScalar(m.LinkInfo.Transceiver, uint8(0))
		}},
		{"modes-compact", "compact mode bitmap", "unknown scalars and compact empty advertised bitmap", EthtoolLinkModesKind, "nltest0", 0, false, func(m EthtoolMessage) bool {
			return modes(0xffffffff, 255)(m) && equalScalar(m.LinkModes.Autoneg, uint8(0)) && m.LinkModes.Ours != nil && m.LinkModes.Ours.Compact && linkWordsAllZero(m.LinkModes.Ours.Value)
		}},
		{"modes-verbose", "verbose mode bitmap", "unknown scalars and verbose empty advertised bitmap", EthtoolLinkModesKind, "nltest0", 0, false, func(m EthtoolMessage) bool {
			return modes(0xffffffff, 255)(m) && equalScalar(m.LinkModes.Autoneg, uint8(0)) && m.LinkModes.Ours != nil && !m.LinkModes.Ours.Compact && len(m.LinkModes.Ours.Bits) == 0
		}},
		{"state", "link detection", "LINK=1 independently of speed", EthtoolLinkStateKind, "nltest0", 0, false, func(m EthtoolMessage) bool { return m.LinkState != nil && equalScalar(m.LinkState.Link, uint8(1)) }},
		{"unsupported", "unsupported loopback operation", "matched EOPNOTSUPP, not speed zero", EthtoolLinkModesKind, "lo", syscall.EOPNOTSUPP, false, nil},
		{"removed", "query deleted device", "matched ENODEV, not a settings reply", EthtoolLinkModesKind, "nlgone", syscall.ENODEV, false, nil},
		{"invalid", "unknown request header flags", "matched EINVAL with extended ACK", EthtoolLinkModesKind, "nltest0", syscall.EINVAL, false, nil},
		{"duplex-half", "half duplex boundary", "100 Mbps / half=0 in reply and notification", EthtoolLinkModesKind, "nltest0", 0, true, modes(100, 0)},
		{"settings-unknown", "unknown sentinels", "uint32 max / duplex 255 preserved", EthtoolLinkModesKind, "nltest0", 0, true, modes(0xffffffff, 255)},
		{"sim-fec", "netdevsim FEC", "auto=0, active link-mode index=51, populated bitset", EthtoolFECKind, "nlsim0", 0, true, func(m EthtoolMessage) bool {
			return m.FEC != nil && equalScalar(m.FEC.Auto, uint8(0)) && equalScalar(m.FEC.Active, uint32(51)) && bitsetValue(m.FEC.Modes, 51)
		}},
		{"sim-pause", "netdevsim pause", "autoneg=0, RX=1, TX=1", EthtoolPauseKind, "nlsim0", 0, true, func(m EthtoolMessage) bool {
			return m.Pause != nil && equalScalar(m.Pause.Autoneg, uint8(0)) && equalScalar(m.Pause.RX, uint8(1)) && equalScalar(m.Pause.TX, uint8(1))
		}},
		{"sim-rings", "netdevsim rings", "RX=128, TX=128", EthtoolRingsKind, "nlsim0", 0, true, func(m EthtoolMessage) bool {
			return m.Rings != nil && equalScalar(m.Rings.RX, uint32(128)) && equalScalar(m.Rings.TX, uint32(128))
		}},
	}
	speeds := []uint32{100000, 200000, 400000, 800000}
	rows := make([]row, 0, len(baseRows)+len(speeds))
	rows = append(rows, baseRows...)
	for _, speed := range speeds {
		rows = append(rows, row{fmt.Sprintf("speed-%d", speed), "virtual high-speed scalar readback", fmt.Sprintf("%d Mbps / full=1, reply and notification", speed), EthtoolLinkModesKind, "nltest0", 0, true, modes(speed, 1)})
	}
	for _, kernel := range []string{"6_8_12", "7_1_4"} {
		for _, tc := range rows {
			t.Run(kernel+"/"+tc.scenario, func(t *testing.T) {
				t.Logf("%s; expected: %s", tc.description, tc.outcome)
				messages := linkCaptureBundle(t, kernel, tc.scenario)
				var familyID uint16
				var requests []linkCaptureMessage
				var replies, notifications, matchedErrors, acks int
				for _, packet := range messages {
					if packet.protocol != unix.NETLINK_GENERIC {
						continue
					}
					h := packet.header
					if h.Type == GenlControllerID && h.Flags&unix.NLM_F_REQUEST == 0 && len(packet.body) > 0 && packet.body[0] == 1 {
						f, err := ParseGenericNetlinkFamily(packet.body)
						if err != nil {
							t.Fatal(err)
						}
						if f.Name == "ethtool" {
							if f.MulticastGroups["monitor"] == 0 || !equalScalar(f.Version, uint32(1)) {
								t.Fatalf("bad discovery: %+v", f)
							}
							familyID = f.ID
						}
						continue
					}
					if h.Type == unix.NLMSG_ERROR {
						if len(packet.body) < 20 {
							t.Fatal("short nlmsgerr")
						}
						_, err := WalkNlMsgs(packet.wire, h.Seq, nil)
						if err == nil {
							acks++
							continue
						}
						for _, request := range requests {
							// Compare the original header inside nlmsgerr. The CLI's
							// request PID may be zero; outer ACK PID is not that PID.
							if bytes.Equal(request.wire[:16], packet.body[4:20]) && h.Seq == request.header.Seq {
								if tc.errno == 0 || !errors.Is(err, tc.errno) {
									t.Fatalf("matched error %v, want %v", err, tc.errno)
								}
								if tc.scenario == "invalid" {
									if h.Flags&unix.NLM_F_ACK_TLVS == 0 {
										t.Fatal("missing extended ACK")
									}
									offset := 20 // errno + original nlmsghdr, when CAPPED
									if h.Flags&unix.NLM_F_CAPPED == 0 {
										offset = 4 + (int(request.header.Len)+3)&^3
									}
									if offset > len(packet.body) {
										t.Fatal("truncated extended ACK")
									}
									attrs, parseErr := ParseNetlinkAttributes(packet.body[offset:])
									if parseErr != nil {
										t.Fatal(parseErr)
									}
									message, parseErr := attrString(attrs, unix.NLMSGERR_ATTR_MSG)
									if parseErr != nil || message == "" {
										t.Fatalf("missing extack diagnostic: %v", parseErr)
									}
								}
								matchedErrors++
								break
							}
						}
						continue
					}
					if familyID == 0 || h.Type != familyID {
						continue
					}
					m, err := ParseEthtool(packet.body, h.Flags)
					if errors.Is(err, ErrUnsupportedEthtool) {
						continue
					} // CLI can ask additional, out-of-scope commands
					if err != nil {
						t.Fatalf("command %d: %v", packet.body[0], err)
					}
					if m.Kind != tc.kind || m.Header.DeviceName != tc.device {
						continue
					}
					if m.Request {
						requests = append(requests, packet)
						continue
					}
					if m.Header.DeviceIndex == nil || *m.Header.DeviceIndex == 0 {
						t.Fatal("missing reply identity")
					}
					if tc.errno != 0 {
						t.Fatal("error scenario returned settings")
					}
					if tc.check(m) {
						if m.Notification {
							notifications++
						} else {
							// A notification with the same payload does not satisfy GET.
							matched := false
							for _, req := range requests {
								if linkFixtureMatchesGET(req, packet, tc.kind, messages) {
									matched = true
								}
							}
							if !matched {
								t.Fatal("unmatched GET reply")
							}
							replies++
						}
					}
				}
				if familyID == 0 || len(requests) == 0 || acks == 0 {
					t.Fatal("missing discovery, request or ACK evidence")
				}
				if tc.errno != 0 {
					if matchedErrors == 0 {
						t.Fatalf("no correlated %v", tc.errno)
					}
				} else if replies == 0 || (tc.notify && notifications == 0) {
					t.Fatalf("no expected outcome: replies=%d notifications=%d", replies, notifications)
				}
			})
		}
	}
}

func linkWordsAllZero(words []uint32) bool {
	for _, w := range words {
		if w != 0 {
			return false
		}
	}
	return true
}
func bitsetValue(b *EthtoolBitset, index uint32) bool {
	if b == nil {
		return false
	}
	if b.Compact {
		return uint64(index/32) < uint64(len(b.Value)) && b.Value[index/32]&(1<<(index%32)) != 0
	}
	for _, bit := range b.Bits {
		if equalScalar(bit.Index, index) {
			return bit.Value
		}
	}
	return false
}

func TestLinkStateRouteKernelFixtures(t *testing.T) {
	rows := []struct {
		scenario, description, outcome string
		required                       []string
	}{
		{"route-lifecycle", "inventory, carrier loss, admin down, rename and delete", "distinct state fields, NEW/DEL, single GET and multipart completion", []string{"carrier-up", "carrier-down", "admin-up", "admin-down", "renamed", "deleted", "single-get", "done"}},
		{"route-move-source", "namespace departure", "DELLINK for nlmove", []string{"move-del"}},
		{"route-move-target", "namespace arrival", "NEWLINK for nlmove", []string{"move-add"}},
	}
	for _, kernel := range []string{"6_8_12", "7_1_4"} {
		for _, tc := range rows {
			t.Run(kernel+"/"+tc.scenario, func(t *testing.T) {
				t.Logf("%s; expected: %s", tc.description, tc.outcome)
				seen := make(map[string]bool)
				for _, packet := range linkCaptureBundle(t, kernel, tc.scenario) {
					if packet.protocol != unix.NETLINK_ROUTE {
						continue
					}
					h := packet.header
					if h.Type == unix.RTM_GETLINK && h.Flags&unix.NLM_F_REQUEST != 0 && h.Flags&unix.NLM_F_DUMP == 0 {
						seen["single-get"] = true
					}
					if h.Type == unix.NLMSG_DONE {
						done, err := WalkNlMsgs(packet.wire, h.Seq, nil)
						if err != nil || !done {
							t.Fatalf("DONE: %v, %v", done, err)
						}
						seen["done"] = true
					}
					if h.Flags&unix.NLM_F_REQUEST != 0 || (h.Type != unix.RTM_NEWLINK && h.Type != unix.RTM_DELLINK) {
						continue
					}
					event, err := ParseRtnetlinkEvent(h.Type, packet.body)
					if err != nil {
						t.Fatal(err)
					}
					e, ok := event.(LinkEvent)
					if !ok {
						t.Fatalf("not a LinkEvent: %T", event)
					}
					v := e.Link
					if v.Index <= 0 || v.Name == "" {
						t.Fatal("missing link identity")
					}
					if v.Name == "nlv0" && e.Action == EventActionAdd {
						if v.HasCarrier && v.Carrier == 1 && v.HasOperState && v.OperState == IfOperUp {
							seen["carrier-up"] = true
						}
						// Both kernels report LOWERLAYERDOWN for this veth peer
						// loss, not the DOWN state of an admin-disabled link.
						if v.HasCarrier && v.Carrier == 0 && v.HasOperState && v.OperState == IfOperLowerLayerDown && !v.IsAdminDown() && v.IsCarrierDown() {
							seen["carrier-down"] = true
						}
						if !v.IsAdminDown() {
							seen["admin-up"] = true
						} else {
							seen["admin-down"] = true
						}
					}
					if v.Name == "nlrenamed" {
						if e.Action == EventActionDel {
							seen["deleted"] = true
						} else {
							seen["renamed"] = true
						}
					}
					if v.Name == "nlmove" {
						if e.Action == EventActionDel {
							seen["move-del"] = true
						} else {
							seen["move-add"] = true
						}
					}
				}
				for _, key := range tc.required {
					if !seen[key] {
						t.Errorf("missing decoded outcome %s", key)
					}
				}
			})
		}
	}
}
