# nix/protos/buf-generate.nix
#
# Wraps `buf generate` as a runnable shell application.
#
# Offline: every codegen plugin is a nix-pinned LOCAL binary (see buf.gen.yaml +
# nix/versions.nix), so `buf generate` never contacts buf's cloud and can't be
# rate-limited. The only network touch is `buf dep update` (BSR module deps,
# pinned in buf.lock) — not the plugin path — so it is still kept out of
# `nix flake check`.
#
# Use:
#   nix run .#regen-protos
#   # or from inside `nix develop`:
#   regen-protos
#
{ pkgs, lib }:

let
  versions = import ../versions.nix { inherit pkgs; };
in
pkgs.writeShellApplication {
  name = "regen-protos";
  runtimeInputs = [
    versions.buf
    # local codegen plugins on PATH for buf.gen.yaml (local:/protoc_builtin:)
    versions.protoc # protoc, for the python/pyi/cpp builtins
    versions.protoc-gen-go
    versions.protoc-gen-go-grpc
    versions.protoc-gen-go-vtproto
    versions.grpc-gateway # protoc-gen-grpc-gateway + protoc-gen-openapiv2
    versions.protoc-gen-dart
    versions.grpc # grpc_python_plugin + grpc_cpp_plugin
  ];
  text = ''
    set -euo pipefail

    if [ ! -f buf.yaml ]; then
      echo "regen-protos: must be run from the xtcp2 repo root (no buf.yaml here)" >&2
      exit 2
    fi

    echo "==> buf dep update"
    buf dep update

    echo "==> buf lint"
    buf lint

    echo "==> buf build"
    buf build

    echo "==> buf generate"
    buf generate

    # Keep the ClickHouse Kafka format schema in lockstep with the canonical
    # proto. ClickHouse decodes the ProtobufList Kafka payload with this file
    # (kafka_schema = 'xtcp_flat_record.proto:xtcp_flat_record.v1.XtcpFlatRecord'),
    # so any field the proto gains must appear here too or ClickHouse silently
    # drops it. It used to be a hand-maintained copy and drifted (missing
    # location / container_id / container_runtime); generating it from the one
    # source of truth makes that class of drift impossible. The canonical proto
    # carries no active buf.validate imports/options, so it is parseable as-is
    # by ClickHouse's protobuf reader.
    # Keep the ClickHouse ProtobufList format schemas + the daemon's runtime copy
    # in lockstep with the canonical proto. ClickHouse decodes the Kafka payload
    # with these files, so any field the proto gains must appear here too or
    # ClickHouse silently drops it. Generating them from the single source of
    # truth makes that class of drift impossible. This absorbs the old
    # check_protos.bash (which hand-diffed/copied these). The canonical protos
    # carry no active buf.validate imports/options, so they are parseable as-is
    # by ClickHouse's protobuf reader.
    echo "==> sync ClickHouse format schemas + runtime copy from canonical protos"
    sync_schema() {
      # $1 = canonical source proto, $2 = destination copy
      local canonical="$1" dest="$2"
      {
        printf '// GENERATED by "nix run .#regen-protos" -- DO NOT EDIT.\n'
        printf '// Source of truth: %s\n' "$canonical"
        printf '// Keeping this a generated copy of the canonical proto prevents\n'
        printf '// drift between what xtcp emits and what downstream consumers\n'
        printf '// (ClickHouse ProtobufList decode / the daemon schema registry) ingest.\n'
        printf '//\n'
        cat "$canonical"
      } > "$dest"
      echo "regen-protos: wrote $dest"
    }
    fmt=build/containers/clickhouse/format_schemas
    sync_schema proto/xtcp_flat_record/v1/xtcp_flat_record.proto "$fmt/xtcp_flat_record.proto"
    sync_schema proto/clickhouse_protolist/v1/clickhouse_protolist.proto "$fmt/clickhouse_protolist.proto"
    # NB: the daemon's cmd/xtcp2/xtcp_flat_record.proto (read at startup and POSTed
    # to the schema registry) is a SYMLINK to the canonical proto, so it is always
    # in sync automatically — do NOT sync it here (writing through the symlink would
    # truncate the canonical source).

    echo "regen-protos: done — review and commit any *.pb.go / *.pb.* / schema drift"
  '';
}
