# nix/protos/buf-generate.nix
#
# Wraps `buf generate` as a runnable shell application.
#
# Impure: buf fetches remote plugins (buf.build/protocolbuffers/go,
# buf.build/grpc-ecosystem/gateway:v2.26.3, …) over the network. Live in the
# dev shell; not part of `nix flake check`.
#
# Use:
#   nix run .#regen-protos
#   # or from inside `nix develop`:
#   regen-protos
#
{ pkgs, lib }:

let
  versions = import ../versions.nix { inherit pkgs; };
in
pkgs.writeShellApplication {
  name = "regen-protos";
  runtimeInputs = [ versions.buf ];
  text = ''
    set -euo pipefail

    if [ ! -f buf.yaml ]; then
      echo "regen-protos: must be run from the xtcp2 repo root (no buf.yaml here)" >&2
      exit 2
    fi

    echo "==> buf dep update"
    buf dep update

    echo "==> buf lint"
    buf lint

    echo "==> buf build"
    buf build

    echo "==> buf generate"
    buf generate

    # Keep the ClickHouse Kafka format schema in lockstep with the canonical
    # proto. ClickHouse decodes the ProtobufList Kafka payload with this file
    # (kafka_schema = 'xtcp_flat_record.proto:xtcp_flat_record.v1.XtcpFlatRecord'),
    # so any field the proto gains must appear here too or ClickHouse silently
    # drops it. It used to be a hand-maintained copy and drifted (missing
    # location / container_id / container_runtime); generating it from the one
    # source of truth makes that class of drift impossible. The canonical proto
    # carries no active buf.validate imports/options, so it is parseable as-is
    # by ClickHouse's protobuf reader.
    echo "==> sync ClickHouse Kafka format schema from canonical proto"
    canonical=proto/xtcp_flat_record/v1/xtcp_flat_record.proto
    ch_schema=build/containers/clickhouse/format_schemas/xtcp_flat_record.proto
    {
      printf '// GENERATED by "nix run .#regen-protos" -- DO NOT EDIT.\n'
      printf '// Source of truth: %s\n' "$canonical"
      printf '// This is the ProtobufList kafka_schema ClickHouse decodes records\n'
      printf '// with; keeping it a generated copy of the canonical proto prevents\n'
      printf '// drift between what xtcp emits and what ClickHouse ingests.\n'
      printf '//\n'
      cat "$canonical"
    } > "$ch_schema"
    echo "regen-protos: wrote $ch_schema"

    echo "regen-protos: done — review and commit any *.pb.go / *.pb.* drift"
  '';
}
