//
// clickhouse_protolist - this proto is for testing how the clickhouse protolist works
//

// Build this using buf build ( https://buf.build/ ), see the buf config in the root folder

// Little reminder on compiling
// https://developers.google.com/protocol-buffers/docs/gotutorial
// go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
// protoc --go_out=paths=source_relative:. xtcppb.proto

// https://protobuf.dev/programming-guides/encoding/#structure

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: clickhouse_protolist/v1/clickhouse_protolist.proto

package clickhouse_protolist

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MyUint32      uint32                 `protobuf:"varint,1,opt,name=my_uint32,json=myUint32,proto3" json:"my_uint32,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_clickhouse_protolist_v1_clickhouse_protolist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_clickhouse_protolist_v1_clickhouse_protolist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_clickhouse_protolist_v1_clickhouse_protolist_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetMyUint32() uint32 {
	if x != nil {
		return x.MyUint32
	}
	return 0
}

// https://clickhouse.com/docs/en/interfaces/formats#protobuflist
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Envelope_Record     `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_clickhouse_protolist_v1_clickhouse_protolist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_clickhouse_protolist_v1_clickhouse_protolist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_clickhouse_protolist_v1_clickhouse_protolist_proto_rawDescGZIP(), []int{1}
}

func (x *Envelope) GetRows() []*Envelope_Record {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Envelope_Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MyUint32      uint32                 `protobuf:"varint,1,opt,name=my_uint32,json=myUint32,proto3" json:"my_uint32,omitempty"` // repeated because clickhouse is funny
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope_Record) Reset() {
	*x = Envelope_Record{}
	mi := &file_clickhouse_protolist_v1_clickhouse_protolist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope_Record) ProtoMessage() {}

func (x *Envelope_Record) ProtoReflect() protoreflect.Message {
	mi := &file_clickhouse_protolist_v1_clickhouse_protolist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope_Record.ProtoReflect.Descriptor instead.
func (*Envelope_Record) Descriptor() ([]byte, []int) {
	return file_clickhouse_protolist_v1_clickhouse_protolist_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Envelope_Record) GetMyUint32() uint32 {
	if x != nil {
		return x.MyUint32
	}
	return 0
}

var File_clickhouse_protolist_v1_clickhouse_protolist_proto protoreflect.FileDescriptor

const file_clickhouse_protolist_v1_clickhouse_protolist_proto_rawDesc = "" +
	"\n" +
	"2clickhouse_protolist/v1/clickhouse_protolist.proto\x12\x17clickhouse_protolist.v1\"%\n" +
	"\x06Record\x12\x1b\n" +
	"\tmy_uint32\x18\x01 \x01(\rR\bmyUint32\"o\n" +
	"\bEnvelope\x12<\n" +
	"\x04rows\x18\x01 \x03(\v2(.clickhouse_protolist.v1.Envelope.RecordR\x04rows\x1a%\n" +
	"\x06Record\x12\x1b\n" +
	"\tmy_uint32\x18\x01 \x01(\rR\bmyUint32B\xcc\x01\n" +
	"\x1bcom.clickhouse_protolist.v1B\x18ClickhouseProtolistProtoP\x01Z\x1a./pkg/clickhouse_protolist\xa2\x02\x03CXX\xaa\x02\x16ClickhouseProtolist.V1\xca\x02\x16ClickhouseProtolist\\V1\xe2\x02\"ClickhouseProtolist\\V1\\GPBMetadata\xea\x02\x17ClickhouseProtolist::V1b\x06proto3"

var (
	file_clickhouse_protolist_v1_clickhouse_protolist_proto_rawDescOnce sync.Once
	file_clickhouse_protolist_v1_clickhouse_protolist_proto_rawDescData []byte
)

func file_clickhouse_protolist_v1_clickhouse_protolist_proto_rawDescGZIP() []byte {
	file_clickhouse_protolist_v1_clickhouse_protolist_proto_rawDescOnce.Do(func() {
		file_clickhouse_protolist_v1_clickhouse_protolist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clickhouse_protolist_v1_clickhouse_protolist_proto_rawDesc), len(file_clickhouse_protolist_v1_clickhouse_protolist_proto_rawDesc)))
	})
	return file_clickhouse_protolist_v1_clickhouse_protolist_proto_rawDescData
}

var file_clickhouse_protolist_v1_clickhouse_protolist_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_clickhouse_protolist_v1_clickhouse_protolist_proto_goTypes = []any{
	(*Record)(nil),          // 0: clickhouse_protolist.v1.Record
	(*Envelope)(nil),        // 1: clickhouse_protolist.v1.Envelope
	(*Envelope_Record)(nil), // 2: clickhouse_protolist.v1.Envelope.Record
}
var file_clickhouse_protolist_v1_clickhouse_protolist_proto_depIdxs = []int32{
	2, // 0: clickhouse_protolist.v1.Envelope.rows:type_name -> clickhouse_protolist.v1.Envelope.Record
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clickhouse_protolist_v1_clickhouse_protolist_proto_init() }
func file_clickhouse_protolist_v1_clickhouse_protolist_proto_init() {
	if File_clickhouse_protolist_v1_clickhouse_protolist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clickhouse_protolist_v1_clickhouse_protolist_proto_rawDesc), len(file_clickhouse_protolist_v1_clickhouse_protolist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clickhouse_protolist_v1_clickhouse_protolist_proto_goTypes,
		DependencyIndexes: file_clickhouse_protolist_v1_clickhouse_protolist_proto_depIdxs,
		MessageInfos:      file_clickhouse_protolist_v1_clickhouse_protolist_proto_msgTypes,
	}.Build()
	File_clickhouse_protolist_v1_clickhouse_protolist_proto = out.File
	file_clickhouse_protolist_v1_clickhouse_protolist_proto_goTypes = nil
	file_clickhouse_protolist_v1_clickhouse_protolist_proto_depIdxs = nil
}
