{
 "title": "xTCP - Socket performance analysis",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "xtcp_counts{type=\"error\"}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "xtcp_counts{type=\"error\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate(xtcp_counts{type=\"error\"}[5m])",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(xtcp_counts{type=\"error\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "xtcp_histograms{quantile=\"0.99\"}",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "xtcp_histograms{quantile=\"0.99\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "xtcp_config_grpc_counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "xtcp_config_grpc_counts", "legendFormat": "__auto" }
   ]
  }
 ]
}