# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clickhouse_list/v1/clickhouse_protolist.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'clickhouse_list/v1/clickhouse_protolist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-clickhouse_list/v1/clickhouse_protolist.proto\x12\x17\x63lickhouse_protolist.v1\"%\n\x06Record\x12\x1b\n\tmy_uint32\x18\x01 \x01(\rR\x08myUint32\"=\n\x08\x45nvelope\x12\x31\n\x03row\x18\x01 \x03(\x0b\x32\x1f.clickhouse_protolist.v1.RecordR\x03rowB\xcc\x01\n\x1b\x63om.clickhouse_protolist.v1B\x18\x43lickhouseProtolistProtoP\x01Z\x1a./pkg/clickhouse_protolist\xa2\x02\x03\x43XX\xaa\x02\x16\x43lickhouseProtolist.V1\xca\x02\x16\x43lickhouseProtolist\\V1\xe2\x02\"ClickhouseProtolist\\V1\\GPBMetadata\xea\x02\x17\x43lickhouseProtolist::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clickhouse_list.v1.clickhouse_protolist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.clickhouse_protolist.v1B\030ClickhouseProtolistProtoP\001Z\032./pkg/clickhouse_protolist\242\002\003CXX\252\002\026ClickhouseProtolist.V1\312\002\026ClickhouseProtolist\\V1\342\002\"ClickhouseProtolist\\V1\\GPBMetadata\352\002\027ClickhouseProtolist::V1'
  _globals['_RECORD']._serialized_start=74
  _globals['_RECORD']._serialized_end=111
  _globals['_ENVELOPE']._serialized_start=113
  _globals['_ENVELOPE']._serialized_end=174
# @@protoc_insertion_point(module_scope)
